### ISSUE TITLE
Where can I see the code of the current google play app version 1.0.1 ?

### ISSUE THREAD

**Issue by hriziya** [rosenpin/AlwaysOnDisplayAmoled#2381]
I do not see any recent commit to this repository. so how do I get the latest source files for v1.0.1 ?
Can you please help with that?

**Comment by rosenpin** [comment]
I stopped updating this repo a while ago because other people kept cloning my app and re-upload it to the Google Play Store and other stores, which is not allowed by my license.
It took too much time from my day to submit notices against those developers and report them for IP infringement to Google, so I decided to stop updating the source code for the meanwhile.
I might start updating in the future. No plans to do this at the moment though.

**Comment by Bubu** [comment]
I'd like to weigh in here. Always on Amoled is build and published by the F-Droid free software repository: https://f-droid.org/packages/com.tomer.alwayson/

All apps there are built from their source code.

It is of course your own decision to continue the development (for now) as closed source but it is always unfortunate when F-Droid cannot then continue updating the app.

**Comment by rosenpin** [comment]
That's right, the app was not updated on F-Droid since Oct 2nd 2016, which is about 2 months before I stopped updating the repo IIRC.
I am sorry, but at the moment there is not much I can do about this, as I explained above.
