### ISSUE TITLE
0.9.5b21 broke features on rooted S6E+

### ISSUE THREAD

**Issue by wilson289296** [rosenpin/AlwaysOnDisplayAmoled#538]
Newest update makes unlocking with fingerprint while AOD is on impossible, must turn on main lock screen, then scan. (Not present previously)
Also no control to force portrait or landscape, is auto rotate regardless of choice in app. (Not present previously)
Previous formatting issues that didn't exist now occur, notifications now left aligned and lower on screen.
Some instances of digital clock font being clipped off on right edge. (Present last version)

**Comment by wilson289296** [comment]
Also, not sure if related but don't have any other apps that would affect this; capacitive keys no longer have backlighting. Have uninstalled, restarted, and reinstalled, but still no lights. When AOD pressing capacitive keys also causes vibration but no action, previously caused no vibration at all.

**Comment by rosenpin** [comment]
Thanks for the detailed feedback.
Most of the issues you described occour because of the "home button to dismiss" functionality I added in this beta.
I don't have a Samsung device so I can't test everything myself.
I will make the home button to dismiss optional in the next version because it seems like it causes a lot of issues.

**Comment by wilson289296** [comment]
All issues have been fixed! Incredible turn around time, by the way, mad props. Cap keys still won't light up, though I doubt it's due to your app. Thanks a lot!

**Comment by rosenpin** [comment]
Awesome!
Glad to hear :)
